legend:
  highLevel: "blue" # высокий уровень (цвет)
  sufficientLevel: "green" # достаточный уровень (цвет)
  intermediateLevel: "yellow" 
  lowLevel: "orange" # низкий уровень (цвет)
  notCertified: "red" # не аттестованный (цвет)
subjects:
  - name: "Русский язык"
    periods:
      - name: "Четверть 1"
        highLevel: 6 # высокий уровень (количество)
        sufficientLevel: 5 # достаточный уровень (количество)
        intermediateLevel: 4 # средний уровень (количество)
        lowLevel: 3 # низкий уровень (количество)
        notCertified: 2 # не аттестованный (количество)
        total: 20 # общее количество
      - name: "Четверть 2"
        highLevel: 3
        sufficientLevel: 3
        intermediateLevel: 9
        lowLevel: 3
        notCertified: 2
        total: 20
      - name: "Четверть 3"
        highLevel: 4
        sufficientLevel: 4
        intermediateLevel: 8
        lowLevel: 3
        notCertified: 2
        total: 20
      - name: "Четверть 4"
        highLevel: 4
        sufficientLevel: 7
        intermediateLevel: 3
        lowLevel: 4
        notCertified: 2
        total: 20
      - name: "Годовой"
        highLevel: 4
        sufficientLevel: 7
        intermediateLevel: 3
        lowLevel: 4
        notCertified: 2
        total: 20
  - name: "Английский язык"
    periods:
      - name: "Четверть 1"
        highLevel: 6 # высокий уровень (количество)
        sufficientLevel: 5 # достаточный уровень (количество)
        intermediateLevel: 4 # средний уровень (количество)
        lowLevel: 3 # низкий уровень (количество)
        notCertified: 2 # не аттестованный (количество)
        total: 20 # общее количество
      - name: "Четверть 2"
        highLevel: 3
        sufficientLevel: 3
        intermediateLevel: 9
        lowLevel: 3
        notCertified: 2
        total: 20
      - name: "Четверть 3"
        highLevel: 4
        sufficientLevel: 4
        intermediateLevel: 8
        lowLevel: 3
        notCertified: 2
        total: 20
  - name: "Математика"
    periods:
      - name: "Четверть 1"
        highLevel: 6 # высокий уровень (количество)
        sufficientLevel: 5 # достаточный уровень (количество)
        intermediateLevel: 4 # средний уровень (количество)
        lowLevel: 3 # низкий уровень (количество)
        notCertified: 2 # не аттестованный (количество)
        total: 20 # общее количество
      - name: "Четверть 2"
        highLevel: 3
        sufficientLevel: 3
        intermediateLevel: 9
        lowLevel: 3
        notCertified: 2
        total: 20
  - name: "История"
    periods:
      - name: "Четверть 1"
        highLevel: 6 # высокий уровень (количество)
        sufficientLevel: 5 # достаточный уровень (количество)
        intermediateLevel: 4 # средний уровень (количество)
        lowLevel: 3 # низкий уровень (количество)
        notCertified: 2 # не аттестованный (количество)
        total: 20 # общее количество